### ISSUE TITLE
Segmentation fault (core dumped) in assign HImage to HalconImage

### ISSUE THREAD

**Issue by elisastefanini** [asr-ros/asr_halcon_bridge#8] opened 2023-02-03 15:44 UTC
Hi! 
I'm trying to integrate Halcon functions in Ros using your Halcon bridge. To start I tried uploading an image and publishing it as sensor_msgs::Image: 

HImage prova("test.png");
HalconImage imageResFinal;
imageResFinal.encoding = "bgr8";
cout<<"Before assignment\n";
*imageResFinal.image = prova;
cout<<"After assignment\n";
image_pub.publish(imageResFinal.toImageMsg());

My problem is that when I run the node in a shell, I get a segmentation error after the output string "Before Assignment" and I don't know why. Could you help me?

**Comment by Tobi2001** [comment] 2023-02-19 14:31
The image member of your imageResFinal object is a pointer which is null when you dereference it here: 
` *imageResFinal.image = prova`
Closing this issue as it looks like a usage issue and not a bug. Feel free to reopen it if the error is related to the library itself.

**Closed as completed by Tobi2001** 2023-02-19 14:31 UTC
